// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiatorForecasting.Data;

#nullable disable

namespace RadiatorForecasting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250116141922_UpdateProductionFactWithStocks")]
    partial class UpdateProductionFactWithStocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RadiatorForecasting.Models.ProductionFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AluminumRadiatorsProduced")
                        .HasColumnType("int");

                    b.Property<int>("AverageTemperature")
                        .HasColumnType("int");

                    b.Property<int>("CompetitorPrice")
                        .HasColumnType("int");

                    b.Property<int>("CopperRadiatorsProduced")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentAluminumStock")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentCopperStock")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyForecastAluminum")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyForecastCopper")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedAluminumStock")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedCopperStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
